name: Sample GitHub Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Azure CLI
        run: |
          # Install the Azure CLI
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Verify Azure CLI installation
        run: |
          # Verify Azure CLI installation
          az --version
      - name: Download and Install Terraform
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install terraform
          # Verify Terraform installation
          terraform --version

      - name: Terraform Init
        run: |
          terraform init

      - name: Terraform Init
        run: |
          terraform plan

      - name: Terraform Init
        run: |
          terraform apply -auto-approve

