name: Sample GitHub Action

on:
  push:
    branches:
      - main

# Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Azure CLI
        run: |
          # Install the Azure CLI
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Verify Azure CLI installation
        run: |
          # Verify Azure CLI installation
          az --version
      - name: Login via Az module
        uses: azure/login@v1
        with:
         creds: ${{secrets.AZURE_WEB_PORTAL}} 
         
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        
      - name: Terraform Init
        run: |
          terraform init

      - name: Terraform plan
        run: |
          terraform plan

      - name: Terraform apply
        run: |
          terraform apply -auto-approve

